openapi: 3.0.0
info:
  title: File Upload API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload a file and retrieve top k frequent words
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                k:
                  type: integer
      responses:
        '200':
          description: File uploaded successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
